### ISSUE TITLE
Adapt for multiple charts

### ISSUE THREAD

**Issue by Piwero** [Piwero/helmseum#11]
This is a general limitation of semantic release, it is by default designed to just maintain one version (one chart in your case). There are solutions for this, e.g. https://github.com/pmowrer/semantic-release-monorepo. I haven't used this myself and can't guarantee it works with this plugin but might be worth to give it a try.

I have used this plugin in previously in a repo with multiple charts, this is how the gitlab ci config looked like

```yaml
.release-helm:
  extends: [.release]  # <-- this was a custom semantic-release job (default should work for you)
  variables:
    PACKAGE_MANAGER: "helm"
    HELM_CHART_REPO: "oci://your-domain.com/project"

release-chart1:
  extends: [.release-helm]
  variables:
    PACKAGE_NAME: "chart2"
    RELEASE_CONTEXT: "./charts/chart1" # <-- this was to run the job in the subdirectory

release-chart2:
  extends: [.release-helm]
  variables:
    PACKAGE_NAME: "chart2"
    RELEASE_CONTEXT: "./charts/chart2"
```

Essentially, you would have a job per chart which is executed inside the subdirectory. I would recommend to first try using public plugins like the monorepo one before implementing a custom solution like I did previously.

_Originally posted by @nflaig in https://github.com/nflaig/semantic-release-helm/issues/33#issuecomment-2143399481_
